# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 从你的全世界路过
subtitle: "世界很暗，但是你来了"
description: "我希望有个如你一般的人。 如这山间清晨一般明亮清爽的人， 如奔赴古城道路上阳光一般的人， 温暖而不炙热，覆盖我所有肌肤。 由起点到夜晚，由山野到书房， 一切问题的答案都很简单。 我希望有个如你一般的人，贯彻未来，数遍生命的公路牌。"
keywords: 前端、免流、技术、运维、手机
author: 记住
language: zh-CN
# timezone: "Asia/GondGuang"

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://heweiliang88.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  [
    _posts/未发布/**/*,
    _posts/爱好/未发布/*,
    _posts/博客/未发布/*,
    _posts/测试/未发布/*,
    _posts/考试/未发布/*,
    _posts/攻防/未发布/*,
    _posts/古汉语/未发布/*,
    _posts/后端/未发布/**/*,
    _posts/计算机408/未发布/*,
    _posts/经济/未发布/*,
    _posts/前端/未发布/*,
    _posts/数据库/未发布/*,
    _posts/数项目/未发布/*,
    _posts/运维/未发布/*,
    _posts/面试/未发布/*,
  ]

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 100
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/

# date_format: YYYY-MM-DD
# time_format: HH:mm:ss
# ## Use post's date for updated date unless set in front-matter
# use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 9
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: " "

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# hexo-tag-cloud
tag_cloud:
  textFont: Trebuchet MS, Helvetica
  textColor: "#333"
  textHeight: 25
  outlineColor: "#E2E1D1"
  maxSpeed: 0.1

## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
# theme: hexo-theme-next
theme: oranges

# live2d:
#   enable: true
#   pluginModelPath: assets/
#   model:
#     use: live2d-widget-model-haru #模板目录，在node_modules里
#   display:
#     position: left
#     #  1:2
#     width: 300
#     height: 600
#   mobile:
#     show: true #是否在手机进行显示

wordCount:
  enable: true # 将这个值设置为 true 即可.
  postWordCount: true
  min2read: true
  totalCount: true

# theme: next
# theme: matery

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:heweiliang88/heweiliang88.github.io.git
    # gitee: git@gitee.com:heweiliang/heweiliang.git
  branch: master

# 音乐播放器
# aplayer:
#   meting: true

#  emoji表情
# githubEmojis:
#   enable: true
#   className: github-emoji
#   inject: true
#   styles:
#   customEmojis:

# 代码光亮
# highlight:
#   enable: true
#   line_number: true
#   auto_detect: true
#   tab_replace: ""
#   wrap: true
#   hljs: false
highlight:
  enable: true
  auto_detect: true
  line_number: true
  line_threshold: 0
  tab_replace: ""
  exclude_languages:
    - example
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ""

# [ele828/hexo-prism-plugin: Hexo plugin for code highlighting by prism.js, supporting JSX syntax](https://github.com/ele828/hexo-prism-plugin)
prism_plugin:
  mode: "preprocess" # realtime/preprocess
  theme: "tomorrow"
  line_number: true # default false
  custom_css:
#  aplayer:
#    meting: true
